# Generated by Django 4.2.5 on 2023-11-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCRUD', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioCRUD',
        ),
    ]
