# Generated by Django 4.2.5 on 2023-11-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCRUD', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='casasAvivamiento',
            fields=[
                ('codCA', models.AutoField(primary_key=True, serialize=False)),
                ('codNom', models.CharField(max_length=40)),
            ],
        ),
    ]
