# Generated by Django 4.2.5 on 2023-11-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCRUD', '0006_casasavivamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocrud',
            name='codCA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appCRUD.casasavivamiento'),
            preserve_default=False,
        ),
    ]
