# Generated by Django 4.2.5 on 2023-11-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCRUD', '0007_usuariocrud_codca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocrud',
            name='codCA',
        ),
        migrations.DeleteModel(
            name='casasAvivamiento',
        ),
        migrations.DeleteModel(
            name='UsuarioCRUD',
        ),
    ]
