# Generated by Django 4.2.5 on 2023-11-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCRUD', '0008_remove_usuariocrud_codca_delete_casasavivamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='casasAvivamiento',
            fields=[
                ('codCA', models.AutoField(primary_key=True, serialize=False)),
                ('codNom', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCRUD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=40)),
                ('comuna', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('numero', models.IntegerField()),
                ('codCA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCRUD.casasavivamiento')),
            ],
        ),
    ]
